INSERT INTO COUNTRY VALUES (1, 'Burundi')
INSERT INTO COUNTRY VALUES (2, 'Malawi')
INSERT INTO COUNTRY VALUES (3, 'Ghana')

INSERT INTO AUTHOR VALUES (1, 'Pierre Shingiro',1)
INSERT INTO AUTHOR VALUES (2, 'Alfred Muhawenayo',1)
INSERT INTO AUTHOR VALUES (3, 'Roy Manda',2)
INSERT INTO AUTHOR VALUES (4, 'Airtel Gama',2)
INSERT INTO AUTHOR VALUES (5, 'Lazarus Nkhata',2)
INSERT INTO AUTHOR VALUES (6, 'Daniel Pasula',2)

INSERT INTO POST VALUES (1, 'Spring Boot with JPA',   1 )
INSERT INTO POST VALUES (2, 'Modern garbage collection',  1 )
INSERT INTO POST VALUES (3, 'Why checked exceptions exist?',  2 )
INSERT INTO POST VALUES (4, 'HTTP server of Java 18',   2 )
INSERT INTO POST VALUES (5, 'Java for machine learning',   2 )
INSERT INTO POST VALUES (6, 'RESTful services in Java',  3 )
INSERT INTO POST VALUES (7, 'The best IDE for Java beginners', 4  )
INSERT INTO POST VALUES (8, 'Integration testing',  4 )
INSERT INTO POST VALUES (9, 'Best Java libraries',   4 )
INSERT INTO POST VALUES (10, 'Cool Java features',   5 )
INSERT INTO POST VALUES (11, 'Final and sealed classes',   5 )
 
insert into POST_LIKES values(1,2)
insert into POST_LIKES values(1,3)
insert into POST_LIKES values(1,4)
insert into POST_LIKES values(2,2)
insert into POST_LIKES values(3,1)
insert into POST_LIKES values(6,1)
insert into POST_LIKES values(6,5)
insert into POST_LIKES values(6,4)
insert into POST_LIKES values(10,2)
insert into POST_LIKES values(10,1)